name: Release and Publish Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create icons directory (if missing)
      run: |
        mkdir -p icons
        # Create placeholder icons if they don't exist
        if [ ! -f "icons/icon16.png" ]; then
          # Generate simple placeholder icons using ImageMagick
          sudo apt-get update
          sudo apt-get install -y imagemagick
          convert -size 16x16 xc:transparent -fill "#4285f4" -draw "rectangle 2,2 14,14" icons/icon16.png
          convert -size 48x48 xc:transparent -fill "#4285f4" -draw "rectangle 6,6 42,42" icons/icon48.png
          convert -size 128x128 xc:transparent -fill "#4285f4" -draw "rectangle 16,16 112,112" icons/icon128.png
        fi
        
    - name: Update manifest version
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        # Update manifest.json with the new version
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" manifest.json
        echo "Updated manifest version to $VERSION"
        
    - name: Create extension package
      run: |
        # Create a zip file containing the extension files
        zip -r github-link-plugin.zip \
          manifest.json \
          content.js \
          icons/ \
          LICENSE \
          README.md
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: |
          ## Changes
          
          Release of GitHub PR Link Copier extension version ${{ github.ref }}.
          
          ## Installation
          
          Download the `github-link-plugin.zip` file and install it in Firefox:
          1. Open Firefox
          2. Go to `about:debugging`
          3. Click "This Firefox"
          4. Click "Load Temporary Add-on"
          5. Select the `manifest.json` file from the extracted zip
          
          ## Firefox Add-ons Store
          
          This extension will be submitted to the Firefox Add-ons store for review.
        draft: false
        prerelease: false
        files: |
          github-link-plugin.zip

    - name: Submit to Firefox Add-ons Store
      if: ${{ secrets.FIREFOX_JWT_ISSUER != '' && secrets.FIREFOX_JWT_SECRET != '' }}
      run: |
        # Install web-ext for Firefox Add-ons submission
        npm install -g web-ext
        
        # Submit to Firefox Add-ons store
        web-ext sign \
          --api-key="${{ secrets.FIREFOX_JWT_ISSUER }}" \
          --api-secret="${{ secrets.FIREFOX_JWT_SECRET }}" \
          --artifacts-dir=./artifacts \
          --source-dir=. \
          --ignore-files=*.zip \
          --ignore-files=.git/ \
          --ignore-files=.github/ \
          --ignore-files=README.md
          
    - name: Upload signed extension (if available)
      if: ${{ secrets.FIREFOX_JWT_ISSUER != '' && secrets.FIREFOX_JWT_SECRET != '' }}
      run: |
        # Upload signed extension to the same release if it exists
        if [ -f "./artifacts/"*.zip ]; then
          gh release upload ${{ github.ref }} ./artifacts/*.zip --clobber
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 